version: '3.3'
services:
      neo4j:
        platform: linux/x86_64
        container_name: neo4j
        image: neo4j:4.3.5
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_AUTH=${NEO4J_PASSWORD}
            - EXTENSION_SCRIPT=import.sh
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true
            - NEO4J_PLUGINS=["apoc", "graph-data-science"]
            - NEO4J_dbms_active__database=call.db
        volumes:
            - ./neo4j_db/data:/data
            - ./neo4j_db/logs:/logs
            - ./neo4j_db/import:/var/lib/neo4j/import
            - ./neo4j_db/plugins:/plugins