version: '3.3'
services:
      neo4j:
        platform: linux/x86_64
        # image: neo4j
        container_name: neo4j-container
        build:
            context: .
            dockerfile: Dockerfile
        # env_file:
        #     ../.env
        # container_name: neo4j
        # # https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8
        # image: neo4j:4.3.5
        ports:
            - 7474:7474
            - 7687:7687
        # environment:
        #     - NEO4J_AUTH=${NEO4J_PASSWORD}
        #     - EXTENSION_SCRIPT=import.sh
        #     - NEO4J_apoc_export_file_enabled=true
        #     - NEO4J_apoc_import_file_enabled=true
        #     # apoc.inport.file.use_neo4j_config=true
        #     # Prefix with NEO4J, repace "." by "_", replace "_" by "__"
        #     - NEO4J_apoc_import_file_use__neo4j__config=true
        #     - NEO4J_PLUGINS=["apoc", "graph-data-science"]
        #     - NEO4J_dbms_active__database=flights.db
            # - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
            # - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*

        # volumes:
        #     - ./neo4j_db/data:/data
        #     - ./neo4j_db/logs:/logs
        #     - ./neo4j_db/import:/var/lib/neo4j/import
        #     - ./neo4j_db/plugins:/plugins